#! /bin/bash

if [ "$1" == "" ]; then
    echo "usage: ./workon <problem_no>"
    exit 1;
fi;

# setup the necessary files
mkdir $1 2> /dev/null && cp template.cpp $1/main.cpp
inputfile="$1/input"
touch $inputfile

while true; do
    filename=$(inotifywait -q --exclude a.out -e modify $1 | cut -d' ' -f3)
    clear
    if [ "$filename" != "main.cpp" ]; then
        inputfile="$1/$filename";
    fi;
    g++ -std=c++11 $1/main.cpp -o $1/a.out && timeout 3 $1/a.out < $inputfile; 
    if [ $? == 124 ]; then
        echo timeout;
    fi;
done;
